### ISSUE TITLE
Clarification regarding Silent Push Notifications

### ISSUE THREAD

**Issue by phal0r** [EinfachHans/capacitor-firebase-push#1]
Hi @EinfachHans ,

thanks for this repo and your work. I also am investigating silent push notifications for Capacitor (especially on iOS). I have to questions regarding this matter:

- Regarding the completionHandler I thought, that we first have to fetch data and then call the handler in order to signal to iOS, that the background operation is finished (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application). How is it working with this plugin? I attach a handler to the "message" event on js side, but from reading the sourcecode, this will be called after the completionHandler. Does this work as intended? Do you use it this way and did you encounter any downsides (i.e. penalties in APNs) with this approach?

- In order to make silent push notifications work, the background-mode "push notifications" is required. I assume, that you did this in your iOS project, but it is not documented here. Is my assumption correct?

Thanks in advance for your response!

**Comment by EinfachHans** [comment]
Hey,

1. Like mentioned in the Shoutout i developed this Plugin with Help from other Plugins. I got the Logic from here: https://github.com/dpa99c/cordova-plugin-firebasex/blob/21aae9e9c50f2c8b2bd41ac9f9164da76e5237b7/src/ios/AppDelegate%2BFirebasePlugin.m#L209 - This is the best working Cordova Plugin for Firebase Push Notifications. I had never problems with it (or this capacitor one)

2. Yes that's correct 😊 Have to add it to the docs in future

**Comment by phal0r** [comment]
Thanks for the quick response. Seems like most implementations do it this way. I was confused why the official push notifications plugin would not support silent push. It is just stated, that native code should be used (https://capacitorjs.com/docs/apis/push-notifications#ios)... strange

If the code is being executed even after calling the completion handler, it will be fine for me aswell.

**Comment by EinfachHans** [comment]
Great, if you have any more issues or questions feel free to open a new Issue 😊
