### ISSUE TITLE
iOS silent / background notifications stop receiving until reboot

### ISSUE THREAD

**Issue by holygekko** [EinfachHans/capacitor-firebase-push#13]
I've been trying for the last few days to get data only / background notifications working. Android works perfectly, but I'm having problems with iOS.

Normal notifications are working fine and always arrive. Data notifications start out fine but then after a while stop working. After a reboot of the device they start working again.

Is this normal behavior? And more importantly does this only happen when testing and not in the production version, downloaded via the app store?

Do you have any experience in this?

**Comment by holygekko** [comment]
@jaco-terbraak, @Novivy, @EinfachHans do you have any experience with this (iOS silent / background notifications)

**Comment by jaco-terbraak** [comment]
If notifications stop working on development, chances are they won't work on production either.

I suspect you might be suffering from this issue: https://github.com/EinfachHans/capacitor-firebase-push/issues/5

**Comment by holygekko** [comment]
I followed the instructions in the readme and added `Messaging.messaging().apnsToken = deviceToken`

This morning it had again stopped working. The app was still in memory. I checked the token I had in the db. After killing and restarting the app the token didn't change and also after rebooting the phone the token didn't change.

After the reboot the silent push notifications started coming trough again.

So something on my phone resets after a reboot and enables silent notifications. Also deleting the app and reinstalling (via testflight) doesn't help. Only rebooting.

I use the FCM Admin SDK for node to send my messages. I tried several formats for defining the message, e.g.:
```
let message = {
    token,
    data,
    android: { priority: 'high' },
    apns: {
        headers: { 'apns-push-type': 'background', 'apns-priority': '5' },
        payload: { aps: { 'content-available': 1 } }
    }
}
```
But that didn't change anything. So now I send it as just `{ token, data }` FCM adds the required `'content-available': 1` automatically.

If you have any ideas or see things I'm doing wrong, any help would be greatly appreciated :)

**Comment by riderx** [comment]
@holygekko i do think is about how Apple think the background task is usefull or not for the user. even the app is in the background the phone can choose to froze the app of not.
And you don't have any way to control that

**Comment by holygekko** [comment]
It's weird. It works better now, but as @riderx said, iOS can (arbitrarily) decide whether or not to allow the silent push notification.

I als found this article [https://swiftsenpai.com/testing/send-silent-push-notifications/](https://swiftsenpai.com/testing/send-silent-push-notifications/) in which the author states:

> Pro Tip:
> 
> I found out that sometimes the app failed to receive the push notifications because `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` is not being called during app launch. In this kind of situation, **restarting your device** should do the trick.

So it's basically normal behavior for iOS? Anyway, love the plugin and I'm very grateful @EinfachHans took the effort to create it! Thank you!
