### ISSUE TITLE
(bug): message event not triggered when app is closed/in background

### ISSUE THREAD

**Issue by Novivy** [EinfachHans/capacitor-firebase-push#9]
# Bug Report

**Current Behavior:**
`message` event is not triggered when app is closed / in background.
I do receive push notifications in any case though.

**Expected Behavior:**
`message` event trigger when app is closed / in background

**Steps to reproduce:**
```
FirebasePush.addListener('message',
    (message) => {

        FirebasePush.setBadgeNumber({count: 1});
    }
);
```

**Environment information:**
- Capacitor version 
	- `3.4.0`
- Dev machine OS and version, e.g.
    - OSX
        - `10.15.7`

**Comment by Novivy** [comment]
Sorry if it's how it is supposed to work. 

After some research it looks like there isn't some reliable way to be 100% sure we get all notifications that was sent when the app was killed.

**Comment by EinfachHans** [comment]
In Background you can receive push messages directly, but only data pushes. When it's closed, it may be that you get the pushs when the app starts next time but dont have to be

**Comment by holygekko** [comment]
@EinfachHans I can't seem to get the data pushes to work. 

I'd like to be able to receive silent data notification when the app is in the background (not killed) without the user having accepted the getPermissions() dialog so I can call my api to get updated data. I've added the 'Background modes' 'remote notifications' capability in xcode.

I use this message format to send via fcm.messaging().send()
```
let message = {
    token,
    data,
    android: { priority: 'high' },
    apns: {
        headers: { 'apns-push-type': 'background', 'apns-priority': '5' },
        payload: { aps: { 'content-available': 1 } }
    }
}
```
This works exactly as planned in android and also shows "messageType": "data", but on ios it never arrives. Doesn't matter if the app is in foreground or background.

The funny thing is a 'normal' notification does arrive on ios (but only when it's in the foreground). Mind you the user still hasn't accepted the getPermissions() dialog (so no sound or popup). I use this message format:
```
let message = {
    token,
    data,
    notification: { title, body },
    android: { priority: 'high', notification: { channel_id: 'default' } },
    apns: {
        headers: { 'apns-priority': '5' },
        payload: { aps: { 'sound': 'default' } }
    }
}
```

This time it has the "messageType": "notification"

Can you show me how you use the plugin to send an ios Background Update Notification?

**Comment by holygekko** [comment]
After restarting my phone all seems to be working like it should. Hopefully above examples can help someone else :) 
@EinfachHans thank you so much for creating such a wonderful plugin!
